events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    client_max_body_size 500M;
    proxy_read_timeout   300s;
    proxy_send_timeout   300s;
    proxy_connect_timeout 60s;

    server {
        listen 80;

        location = /ai-controller { return 301 /ai-controller/; }
        location /ai-controller/ {
            proxy_pass         http://ai-controller:8000/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_buffering    off;
        }

        location /ai/ {
            proxy_pass         http://ai-controller:8000/api/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
        }

        location = /ai-panel.html {
            root      /usr/share/nginx/html;
            add_header Cache-Control no-store;
        }

        location /orthanc/ {
            proxy_pass         http://orthanc:8042/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_buffering    off;
        }

        location = /simulator { return 301 /simulator/; }
        location /simulator/ {
            proxy_pass         http://simulator:8001/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location = /ris { return 301 /ris/; }
        location /ris/ {
            proxy_pass         http://ris:8002/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass         http://ohif:80;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }
    }
}
