events {
    worker_connections 1024;
}

http {
    upstream orthanc        { server orthanc:8042; }
    upstream ohif           { server ohif:80; }
    upstream ris            { server ris:8002; }
    upstream ai_controller  { server ai-controller:8000; }
    upstream simulator      { server simulator:8001; }
    upstream ehr            { server ehr:8003; }
    upstream lis            { server lis:8004; }
    upstream fhir_bridge    { server fhir-bridge:8005; }

    server {
        listen 80;
        client_max_body_size 0;

        location /orthanc/ {
            proxy_pass          http://orthanc/;
            proxy_set_header    Host              $host;
            proxy_set_header    X-Real-IP         $remote_addr;
            proxy_request_buffering off;
            proxy_buffering         off;
            proxy_read_timeout      300s;
        }

        location /ris/ {
            proxy_pass          http://ris/;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Forwarded-Prefix /ris;
        }

        location /ai-controller/ {
            proxy_pass          http://ai_controller/;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Forwarded-Prefix /ai-controller;
        }

        location /simulator/ {
            proxy_pass          http://simulator/;
            proxy_set_header    Host $host;
        }

        location /ehr/ {
            proxy_pass          http://ehr/;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Forwarded-Prefix /ehr;
        }

        location /lis/ {
            proxy_pass          http://lis/;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Forwarded-Prefix /lis;
        }

        location /fhir-bridge/ {
            proxy_pass          http://fhir_bridge/;
            proxy_set_header    Host $host;
        }

        location / {
            proxy_pass          http://ohif/;
            proxy_set_header    Host $host;
        }
    }
}
