#!/bin/sh
# Wrapper entrypoint for OpenELIS — creates a JVM-level hosts file so that
# Java resolves "localhost" to the Docker host gateway (nginx on port 80).
#
# Spring Security's OIDC discovery fetches
# http://localhost/keycloak/realms/openhis/.well-known/openid-configuration
# The OS resolver always maps localhost → 127.0.0.1 (glibc hardcoded),
# but the JVM can use a custom file via -Djdk.net.hosts.file.
#
# Because this file replaces ALL JVM DNS, we must also include every Docker
# hostname the app needs (openelis-db, keycloak, etc.).

JAVA_HOSTS="/tmp/java-hosts"

# Extract the host-gateway IP from /etc/hosts (added by extra_hosts directive)
GATEWAY_IP=$(awk '/localhost/ && !/^127\./ && !/^::/' /etc/hosts | awk '{print $1}' | head -1)

if [ -z "$GATEWAY_IP" ]; then
    echo "[entrypoint-wrapper] WARNING: No host-gateway IP found, skipping JVM hosts override"
    exec /docker-entrypoint.sh "$@"
fi

echo "[entrypoint-wrapper] Building JVM hosts file: localhost → $GATEWAY_IP"

# Start with the gateway override for localhost
cat > "$JAVA_HOSTS" <<EOF
# Generated by entrypoint-wrapper.sh
# localhost → Docker host gateway (nginx)
$GATEWAY_IP localhost
EOF

# Copy all OTHER entries from /etc/hosts (container IP, etc.)
awk '!/localhost/ && !/^#/ && NF' /etc/hosts >> "$JAVA_HOSTS"

# Resolve Docker service hostnames the app needs and add them.
# getent hosts uses the container's DNS resolver (Docker embedded DNS).
for host in openelis-db keycloak redis nginx; do
    resolved=$(getent hosts "$host" 2>/dev/null | awk '{print $1}')
    if [ -n "$resolved" ]; then
        echo "$resolved $host" >> "$JAVA_HOSTS"
    fi
done

echo "[entrypoint-wrapper] JVM hosts file contents:"
cat "$JAVA_HOSTS"

export CATALINA_OPTS="$CATALINA_OPTS -Djdk.net.hosts.file=$JAVA_HOSTS"

# ── Apply class patches (background watcher) ─────────────────────────────────
# The stock CustomFormAuthenticationSuccessHandler doesn't handle OAuth2
# principals — it only processes UserDetails (form login). Our patched version
# delegates OAuth2 to CustomSSOAuthenticationSuccessHandler which auto-provisions.
#
# IMPORTANT: We must NOT mkdir/copy before Tomcat starts — creating directories
# under webapps/ prevents proper WAR extraction (87ms vs ~10s). Instead, a
# background watcher waits for WAR extraction to complete, then copies patches
# before Spring context initialization loads the classes (~15-30s after WAR).
PATCH_DIR="/opt/patches"
TARGET_DIR="/usr/local/tomcat/webapps/OpenELIS-Global/WEB-INF/classes/org/openelisglobal/security/login"
WAR_MARKER="/usr/local/tomcat/webapps/OpenELIS-Global/WEB-INF/web.xml"

(
    # Wait for WAR to be fully extracted — poll for the ORIGINAL class file,
    # not just web.xml, to avoid racing with the extractor.
    ORIGINAL="$TARGET_DIR/CustomFormAuthenticationSuccessHandler.class"
    echo "[patch-watcher] Waiting for WAR extraction (looking for original class)..."
    for i in $(seq 1 180); do
        if [ -f "$ORIGINAL" ]; then
            # Small delay to ensure extraction is fully settled
            sleep 2
            echo "[patch-watcher] WAR classes extracted after ${i}s, applying patches..."
            for patch in CustomFormAuthenticationSuccessHandler.class CustomSSOAuthenticationSuccessHandler.class; do
                if [ -f "$PATCH_DIR/$patch" ]; then
                    cp "$PATCH_DIR/$patch" "$TARGET_DIR/$patch"
                    chown tomcat_admin:tomcat "$TARGET_DIR/$patch"
                    chmod 644 "$TARGET_DIR/$patch"
                    echo "[patch-watcher] Patched $patch ($(wc -c < "$TARGET_DIR/$patch") bytes)"
                fi
            done
            break
        fi
        sleep 1
    done
) &

exec /docker-entrypoint.sh "$@"
