"""
Unit tests for `opm init` secret coverage (T-10, F#45/F#46).

Covers:
- --non-interactive --auto-generate writes all required secrets (≥32 chars)
- --non-interactive --prompt without explicit values exits 1 listing them
- post-write validation rejects CHANGE_ME_BEFORE_DEPLOY and weak values
- comments from .env.example survive into the written .env
- generated secret values never appear on stdout/stderr
"""
import re

import pytest
from click.testing import CliRunner

import opm

#: Strong value satisfying the ≥16-chars / ≥3-classes check.
_STRONG = "Aa1-0123456789abcdefXYZ"


def _all_output(result) -> str:
    """CliRunner stdout + stderr regardless of the click version's capture mode."""
    output = result.output
    try:
        output += result.stderr
    except (ValueError, AttributeError):
        pass  # mix_stderr=True (click<8.2): stderr is already in .output
    return output


def _run_init(tmp_path, *extra_args):
    runner = CliRunner()
    return runner.invoke(
        opm.cli,
        ["init", "--non-interactive", "--output-dir", str(tmp_path), *extra_args],
    )


# ── required-secret coverage ─────────────────────────────────────────────────

def test_required_secrets_cover_weak_compose_fallback_credentials():
    """Secrets whose compose `${VAR:-default}` fallbacks are publicly known
    weak credentials must be generated by init (F#45/F#46 follow-up):
    - OPENMRS_PASSWORD  seeds the OpenMRS admin account (default Admin123)
    - OPENELIS_PASSWORD seeds the OpenELIS admin account (default adminADMIN!,
      UI host-published on :8082)
    - REDIS_PASSWORD    empty default = no Redis AUTH; init enables it
    """
    for key in ("OPENMRS_PASSWORD", "OPENELIS_PASSWORD", "REDIS_PASSWORD"):
        assert key in opm._REQUIRED_SECRETS, f"{key} missing from _REQUIRED_SECRETS"


# ── auto-generate (default) ───────────────────────────────────────────────────

def test_auto_generate_populates_all_required_secrets(tmp_path):
    result = _run_init(tmp_path)
    assert result.exit_code == 0, _all_output(result)

    env = opm._read_env(tmp_path / ".env")
    for key in opm._REQUIRED_SECRETS:
        value = env.get(key, "")
        assert len(value) >= 32, f"{key} not auto-generated (value too short)"
        assert value != opm._CHANGEME_SENTINEL
        assert opm._check_secret_strength(value)


def test_auto_generated_env_meets_acceptance_grep(tmp_path):
    """≥15 lines match ^[A-Z0-9_]+=[A-Za-z0-9_-]{32,} (plan acceptance criterion;
    the plan's original [A-Z_]+ key class missed the digit in HL7_*)."""
    result = _run_init(tmp_path)
    assert result.exit_code == 0, _all_output(result)

    pattern = re.compile(r"^[A-Z0-9_]+=[A-Za-z0-9_-]{32,}$")
    text = (tmp_path / ".env").read_text()
    matches = [line for line in text.splitlines() if pattern.match(line)]
    assert len(matches) >= len(opm._REQUIRED_SECRETS)

    # No ACTIVE assignment may keep the sentinel (comments may mention it).
    active_sentinels = [
        line for line in text.splitlines()
        if not line.lstrip().startswith("#") and line.endswith(opm._CHANGEME_SENTINEL)
    ]
    assert active_sentinels == []


def test_secret_values_never_printed(tmp_path):
    result = _run_init(tmp_path)
    assert result.exit_code == 0, _all_output(result)

    env = opm._read_env(tmp_path / ".env")
    output = _all_output(result)
    for key in opm._REQUIRED_SECRETS:
        assert env[key] not in output, f"secret value of {key} leaked to console"


# ── --non-interactive --prompt without values ────────────────────────────────

def test_non_interactive_prompt_mode_fails_listing_missing(tmp_path):
    result = _run_init(tmp_path, "--prompt")
    assert result.exit_code == 1
    output = _all_output(result)
    # Every required secret must be named (via its flag alias or env var name)
    for key in opm._REQUIRED_SECRETS:
        alias = opm._LEGACY_FLAG_KEYS.get(key, f"{key} env var")
        assert alias in output, f"missing-secret message lacks {key}"
    assert not (tmp_path / ".env").exists()


def test_non_interactive_prompt_mode_succeeds_with_env_vars(tmp_path, monkeypatch):
    for key in opm._REQUIRED_SECRETS:
        monkeypatch.setenv(key, f"{_STRONG}-{key.lower()}")
    result = _run_init(tmp_path, "--prompt")
    assert result.exit_code == 0, _all_output(result)

    env = opm._read_env(tmp_path / ".env")
    for key in opm._REQUIRED_SECRETS:
        assert env[key] == f"{_STRONG}-{key.lower()}"


# ── post-write validation ─────────────────────────────────────────────────────

def test_validation_rejects_sentinel_left_in_env(tmp_path):
    (tmp_path / ".env").write_text(
        f"SOME_LEGACY_SECRET={opm._CHANGEME_SENTINEL}\n"
    )
    result = _run_init(tmp_path)
    assert result.exit_code == 1
    assert "SOME_LEGACY_SECRET" in _all_output(result)


def test_no_validate_optout_allows_sentinel(tmp_path):
    (tmp_path / ".env").write_text(
        f"SOME_LEGACY_SECRET={opm._CHANGEME_SENTINEL}\n"
    )
    result = _run_init(tmp_path, "--no-validate")
    assert result.exit_code == 0, _all_output(result)


def test_validation_rejects_weak_supplied_password(tmp_path):
    result = _run_init(tmp_path, "--postgres-pass", "hunter2")
    assert result.exit_code == 1
    assert "POSTGRES_PASSWORD" in _all_output(result)


# ── comment round-trip ────────────────────────────────────────────────────────

def test_comments_from_env_example_survive(tmp_path):
    result = _run_init(tmp_path)
    assert result.exit_code == 0, _all_output(result)

    text = (tmp_path / ".env").read_text()
    # Representative comment lines from .env.example
    assert text.startswith("# ⚠️  SECURITY:")
    assert "# ── Keycloak ─" in text
    assert "# ── Deployment profiles ─" in text


def test_existing_env_keys_and_comments_preserved(tmp_path):
    (tmp_path / ".env").write_text(
        "# my custom note\nCUSTOM_FLAG=keep-me\n"
    )
    result = _run_init(tmp_path)
    assert result.exit_code == 0, _all_output(result)

    text = (tmp_path / ".env").read_text()
    assert "# my custom note" in text
    assert "CUSTOM_FLAG=keep-me" in text
    # New secrets appended even though the layout didn't declare them
    env = opm._read_env(tmp_path / ".env")
    for key in opm._REQUIRED_SECRETS:
        assert key in env


# ── helpers ───────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("value,expected", [
    ("short-Aa1", False),                  # < 16 chars
    ("aaaaaaaaaaaaaaaaaaaa", False),       # one class
    ("aaaaaaaaaa1111111111", False),       # two classes
    ("Aa1aaaaaaaaaaaaaaaaa", True),        # three classes
    ("Aa1-aaaaaaaaaaaaaaaa", True),        # four classes
])
def test_check_secret_strength(value, expected):
    assert opm._check_secret_strength(value) is expected


def test_generate_secret_is_strong_and_unique():
    values = {opm._generate_secret() for _ in range(8)}
    assert len(values) == 8
    for value in values:
        assert opm._check_secret_strength(value)
        assert len(value) >= 32
